spring:
  application:
    name: user-server
  #上传文件和数据大小限制，过去是http
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  #数据源配置
  datasource:
    name: junson_personal
    url: jdbc:mysql://localhost:3306/junson_personal?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

#授权
security:
  oauth2:
    resource:
      #获取当前Token的用户信息
      user-info-uri: http://localhost:5400/uaa/users/current
    client:
      clientId: user-server
      clientSecret: 123456
      #获取Token
      accessTokenUri: http://localhost:5400/uaa/oauth/token
      grant-type: client_credentials,password
      #授权作用域
      scope: server

#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  #mybatis项目用pojo来映射持久层,jpa项目用domain
  type-aliases-package: com.junson.lifestream.user.pojo
  configuration:
    #下划线转camel
    mapUnderscoreToCamelCase: true

#注册中心配置
eureka:
  port: 5555
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:5555/eureka/eureka，http://localhost:6666/eureka/eureka 多个注册中心时
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/eureka

